CLASS zcl_abe_bal_converter_gelf DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_abe_bal_converter_gelf IMPLEMENTATION.
ENDCLASS.
