CLASS zcl_abe_bal_converter_loki DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_abe_bal_converter_loki IMPLEMENTATION.
ENDCLASS.
